import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Or whatever font is default
import "./globals.css";
import Navbar from "./Navbar"; // <--- 1. Import this

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar /> {/* <--- 2. Add this here, ABOVE children */}
        <main className="pt-20"> {/* Add padding-top so content isn't hidden behind the fixed nav */}
          {children}
        </main>
      </body>
    </html>
  );
}
